const MIN_CAR_NAME_LENGTH = 1;
const MAX_CAR_NAME_LENGTH = 5;
const MIN_RANDOM_NUMBER = 0;
const MAX_RANDOM_NUMBER = 9;
const MOVE_CONDITION_NUMBER = 4;

export {
  MIN_CAR_NAME_LENGTH,
  MAX_CAR_NAME_LENGTH,
  MIN_RANDOM_NUMBER,
  MAX_RANDOM_NUMBER,
  MOVE_CONDITION_NUMBER,
};
