const MAX_LENGTH_CAR_NAME = 5;

const MIN_COUNT_CAR = 1;
const MIN_RANGE_RACING_COUNT = 1;

const MAX_NUMBER_IN_RANGE = 9;
const MIN_NUMBER_IN_RANGE = 1;
const MOVE_THRESHOLD = 4;

export {
  MAX_LENGTH_CAR_NAME,
  MIN_COUNT_CAR,
  MIN_RANGE_RACING_COUNT,
  MAX_NUMBER_IN_RANGE,
  MIN_NUMBER_IN_RANGE,
  MOVE_THRESHOLD,
};
